name: Build XMRig Windows by Sats

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install vcpkg & dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install libuv openssl hwloc
        shell: pwsh

      - name: Install CMake & Ninja
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install ninja --yes
        shell: pwsh

      - name: Configure & Build with vcpkg toolchain
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          ninja
        shell: pwsh

      - name: Package Output
        run: |
          Compress-Archive -Path build\xmrig.exe -DestinationPath xmrig-windows.zip
        shell: pwsh

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: custom-release
          files: xmrig-windows.zip
          replace: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
