name: Build XMRig Windows by Sats

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install ninja git --yes

      - name: Configure and Build (disable HWLOC)
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DWITH_HWLOC=OFF
          ninja

      - name: Package Output
        run: |
          Compress-Archive -Path build\xmrig.exe -DestinationPath xmrig-windows.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: custom-release
          files: xmrig-windows.zip
          replace: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
